name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout Dockerfile repository
      uses: actions/checkout@v2
      with:
        repository: Hyldem0er/Skirnir-Docker-Image
        path: https://github.com/Hyldem0er/Skirnir-Docker-Image/tree/main/Docker/docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: Docker/docker/Skirnirfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/skirnir:latest
